name: Deploy

# Trigger the workflow on push and pull request events on the main branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Navigate to your project folder on the VPS
            cd ~/Court_Frontend
            
            # Make sure the deploy script is executable
            chmod +x .scripts/deploy.sh
            
            # Run the deploy script
            ./.scripts/deploy.sh
